name: Swift

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: ENV
      run: |
        uname -a
        xcodebuild -version
        swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
